server:
  port: 8585

spring:
  application:
    name: stocks-data-manager
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        jdbc:
          batch_size: 200
          order_inserts: true
          order_updates: true
          lob:
            non-contextual-creation: true
  datasource:
    url: jdbc:postgresql://localhost/stocks
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

base.url: ${BASE_URL}
api.token: ${API_TOKEN}